### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by ragauskl** [GeoTIFF/georaster#38]
**Describe the bug**
Error is not catched withing the package, therefore it keep initial method, where it was called, hanging. Console log 'UnhandledPromiseRejectionWarning:' as in 2 examples below:

`(node:26504) UnhandledPromiseRejectionWarning: TypeError: Invalid byte order value.
    at Function.<anonymous> (C:\Users\ragau\Desktop\testing\tiff-server\node_modules\georaster\dist\georaster.bundle.min.js:8:454885)`

`(node:26504) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'GeographicTypeGeoKey' of null    at C:\Users\ragau\Desktop\testing\tiff-server\node_modules\georaster\dist\georaster.bundle.min.js:8:443308`

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to parse a file buffer of an image that does not have geo data

**Expected behavior**
A error should be thrown/returned in a way where it can be caught by calling method

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Environment: Node
 - Version 0.5.2

**Comment by DanielJDufour** [comment]
Hi, @ragauskl .  Thanks for posting this issue!  Could you share with us an example of a file that is causing this issue, so that we could write a test for it?  You're also welcome to open up a pull request fixing this error handling! Have a great day.

**Comment by ragauskl** [comment]
Example that was hanging
```ts
import * as fs from 'fs-extra'
import * as parseGeoraster from 'georaster'

(async () => {
  // File can be a tiff without geolocation (getGeoKeys() returns empty props)
  // or non tiff file (fromArratBuffer will fail)  
  const buffer = await fs.readFile(req.file.path)
  const data = await parseGeoraster(buffer, undefined, true)
})
```

**Comment by DanielJDufour** [comment]
Just published a new version of GeoRaster that includes your fixes. Thank you!

https://www.npmjs.com/package/georaster
