### ISSUE TITLE
Render to a specific zoom/pyramid level?

### ISSUE THREAD

**Issue by martinhschei** [GeoTIFF/georaster#53]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
When i call parseGeoraster() i would like to be able to specify which "pyramid level" i want to be rendered initially.

**Describe alternatives you've considered**
Nothing.

**Additional context**
It might be possible already - but i have not been able to figure out if it is.

**Comment by DanielJDufour** [comment]
Hi, @martinhschei .   I'm terribly sorry for the late reply.  This is an excellent question.  Are you passing in an array buffer or a url to a GeoTIFF.  If you are passing in a URL to a GeoTIFF, you can call getValues with a width and height and it will automatically determine which pyramid/overview level to use based on the size.  Technically, this is handled by the excellent [geotiff.js](https://github.com/geotiffjs/geotiff.js) library that georaster wraps around.

I'm currently working on a massive rework of GeoRaster, which I hope to publish within the next few months.  I'll incorporate this feedback into this work, so you should be able to specify a specific pyramid/overview level then.

Thank you for your patience and let me know if you have any further questions.

**Comment by martinhschei** [comment]
Great! Looking forward to the new version then!
